# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170122_1509'),
        ('cms', '0003_auto_20170122_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginahome',
            name='highlights2_icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights2icon', to='content.IconContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='highlights2_texto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights2texto', to='content.TextContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='highlights2_titulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights2titulo', to='content.TitleContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='highlights3_icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights3icon', to='content.IconContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='highlights3_texto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights3texto', to='content.TextContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='highlights3_titulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights3titulo', to='content.TitleContent'),
        ),
    ]
