# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170122_1509'),
        ('cms', '0004_auto_20170122_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginahome',
            name='giganticheading_titulo_grande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giganticheadingtitulogrande', to='content.TitleContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='giganticheading_titulo_pequeno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giganticheadingtitulopequeno', to='content.TitleContent'),
        ),
    ]
