# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170122_1509'),
        ('cms', '0005_auto_20170122_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginahome',
            name='posts1_imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1_imagen', to='content.ImageContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts1_texto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1_texto', to='content.TextContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts1_titulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1_titulo', to='content.TitleContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts2_imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts2_imagen', to='content.ImageContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts2_texto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts2_texto', to='content.TextContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts2_titulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts2_titulo', to='content.TitleContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts3_imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts3_imagen', to='content.ImageContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts3_texto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts3_texto', to='content.TextContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts3_titulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts3_titulo', to='content.TitleContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts4_imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts4_imagen', to='content.ImageContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts4_texto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts4_texto', to='content.TextContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='posts4_titulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts4_titulo', to='content.TitleContent'),
        ),
    ]
