# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170122_1509'),
        ('cms', '0006_auto_20170122_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginahome',
            name='CTA_enlace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CTAurl', to='content.LinkContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='CTA_texto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CTAtext', to='content.TextContent'),
        ),
        migrations.AddField(
            model_name='paginahome',
            name='CTA_titulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CTAtitulo', to='content.TitleContent'),
        ),
    ]
