# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconcontent',
            name='form',
        ),
        migrations.RemoveField(
            model_name='linkcontent',
            name='form',
        ),
        migrations.RemoveField(
            model_name='socialcontent',
            name='form',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='form',
        ),
        migrations.RemoveField(
            model_name='titlecontent',
            name='form',
        ),
    ]
