# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_imagecontent_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
